[package]
name = "cmbr"
version = "0.0.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
clap_complete = "4.5.5"
exec = "0.3.1"
micromap = "0.0.15"
smartstring = "1.0.1"
smol_str = "0.2.2"

[profile.release]
opt-level = 3
strip = true
debug-assertions = false
overflow-checks = false
lto = "fat"
incremental = true
codegen-units = 1

[profile.dev]
opt-level = 1
lto = "thin"
incremental = true
codegen-units = 2048

[profile.bolt]
inherits = "release"
strip = false

[profile.size]
inherits = "release"
opt-level = "s"

[profile.size_extreme]
inherits = "release"
opt-level = "z"