[graph]
targets = [
    "x86_64-unknown-linux-musl",
    "x86_64-unknown-linux-gnu",
]
all-features = false

[output]
feature-depth = 1

[advisories]
ignore = []

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "GPL-3.0",
]

confidence-threshold = 0.8

[licenses.private]
ignore = false
registries = []

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
deny = [
    { crate = "git2", use-instead = "gix" },
    { crate = "openssl", use-instead = "rustls" },
    { crate = "openssl-sys", use-instead = "rustls" },
    { crate = "cmake", use-instead = "cc" },
]
skip = []
skip-tree = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = ["https://github.com/datawater/pgn-lexer"]
